version: 2
updates:
- package-ecosystem: cargo
  directories:
    - "/"
    - "/staging/"
  schedule:
    interval: weekly
  allow:
    - dependency-name: "vhost"
    - dependency-name: "vhost-user-backend"
    - dependency-name: "virtio-bindings"
    - dependency-name: "virtio-queue"
    - dependency-name: "virtio-vsock"
    - dependency-name: "vm-memory"
    - dependency-name: "vmm-sys-util"
  groups:
      rust-vmm:
        patterns:
          - "*"
- package-ecosystem: cargo
  directories:
    - "/"
    - "/staging/"
  schedule:
    interval: monthly
  allow:
    - dependency-type: all
  ignore:
    - dependency-name: "vhost"
    - dependency-name: "vhost-user-backend"
    - dependency-name: "virtio-bindings"
    - dependency-name: "virtio-queue"
    - dependency-name: "virtio-vsock"
    - dependency-name: "vm-memory"
    - dependency-name: "vmm-sys-util"
  groups:
      non-rust-vmm:
        patterns:
          - "*"
  # Makes it possible to have another config for the same directory.
  # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
  target-branch: main

- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
